name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main  # Adjust if your default branch is different
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: self-hosted
    name: Build and Deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # recommended LTS version
          cache: 'npm' # Enable Node modules caching

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        
      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Set Wrangler Secrets
        run: |
          npx wrangler secret put HASSIO_URL --name react-demo-1 << EOF
          ${{ secrets.HASSIO_URL }}
          EOF
          npx wrangler secret put HASSIO_TOKEN --name react-demo-1 << EOF
          ${{ secrets.HASSIO_TOKEN }}
          EOF
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Publish Worker to Cloudflare
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
          fi
