name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # your runner is self-hosted (macOS ARM64)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Clear and Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy Worker
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
